### ISSUE TITLE
[BUG] Responsive issue on Certain screen sizes

### ISSUE THREAD

**Issue by Daaaaaany** [Swaggy-Swagger/swaggy-ui#5]
## 🐞Bug Report
In the current responsive UI, there seems to be a display issue on certain screen sizes. Some elements of the layout are not rendering as expected, causing the page to break or look misaligned.

### Describe the Bug 
<img width="922" alt="image" src="https://github.com/user-attachments/assets/8e3be1f0-aea4-4e70-acd7-e08d02866302">

### ETC
I believe I can fix this issue with some minor adjustments to the media queries and layout. Should I go ahead and make the changes?

**Comment by westofsky** [comment]
Thank you for reporting this issue!
It would be great if you could fix it. Please go ahead and submit the updated code. Once you’ve done that, I’ll review and build it before merging. Appreciate your help in improving the UI!

**Comment by Jeevan-Neupane** [comment]
Can you assign this to me I want to work in it.

**Comment by hyunihs** [comment]
> Can you assign this to me I want to work in it.

I've assigned you to the issue! @Jeevan-Neupane

**Comment by westofsky** [comment]
@nilesh-fatfatwale 
Could you please review the current UI for possible improvements to enhance the user experience? I think some adjustments might make it more intuitive and user-friendly. Thanks!
